
Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: /var/hyperledger/orderer/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"
        OrdererEndpoints:
            - healthcare_orderer.example.com:13050

    PatientOrg:
        <<: *OrgDefaults
        Name: PatientMSP
        ID: PatientMSP
        MSPDir: crypto-config/peerOrganizations/patient.example.com/msp
        AnchorPeers:
            - Host: peer0.patient.example.com
              Port: 7051
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('PatientMSP.admin', 'PatientMSP.client', 'PatientMSP.peer')"
            Writers:
                Type: Signature
                Rule: "OR('PatientMSP.admin', 'PatientMSP.client', 'PatientMSP.peer')"
            Admins:
                Type: Signature
                Rule: "OR('PatientMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('PatientMSP.peer')"
    HospitalOrg:
        <<: *OrgDefaults
        Name: HospitalMSP
        ID: HospitalMSP
        MSPDir: crypto-config/peerOrganizations/hospital.example.com/msp
        AnchorPeers:
            - Host: peer0.hospital.example.com
              Port: 8051
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('HospitalMSP.admin', 'HospitalMSP.client', 'HospitalMSP.peer')"
            Writers:
                Type: Signature
                Rule: "OR('HospitalMSP.admin', 'HospitalMSP.client', 'HospitalMSP.peer')"
            Admins:
                Type: Signature
                Rule: "OR('HospitalMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('HospitalMSP.peer')"
    LaboratoryOrg:
        <<: *OrgDefaults
        Name: LaboratoryMSP
        ID: LaboratoryMSP
        MSPDir: crypto-config/peerOrganizations/laboratory.example.com/msp
        AnchorPeers:
            - Host: peer0.laboratory.example.com
              Port: 9051
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('LaboratoryMSP.admin', 'LaboratoryMSP.client', 'LaboratoryMSP.peer')"
            Writers:
                Type: Signature
                Rule: "OR('LaboratoryMSP.admin', 'LaboratoryMSP.client', 'LaboratoryMSP.peer')"
            Admins:
                Type: Signature
                Rule: "OR('LaboratoryMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('LaboratoryMSP.peer')"
    InsuranceOrg:
        <<: *OrgDefaults
        Name: InsuranceMSP
        ID: InsuranceMSP
        MSPDir: crypto-config/peerOrganizations/insurance.example.com/msp
        AnchorPeers:
            - Host: peer0.insurance.example.com
              Port: 10051
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('InsuranceMSP.admin', 'InsuranceMSP.client', 'InsuranceMSP.peer')"
            Writers:
                Type: Signature
                Rule: "OR('InsuranceMSP.admin', 'InsuranceMSP.client', 'InsuranceMSP.peer')"
            Admins:
                Type: Signature
                Rule: "OR('InsuranceMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('InsuranceMSP.peer')"
    PharmacyOrg:
        <<: *OrgDefaults
        Name: PharmacyMSP
        ID: PharmacyMSP
        MSPDir: crypto-config/peerOrganizations/pharmacy.example.com/msp
        AnchorPeers:
            -



