version: '2'

services:

  healthcare_orderer.example.com:
    container_name: healthcare_orderer.example.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_ORDERERTYPE=kafka
      - ORDERER_GENERAL_KAFKA_BROKERS=kafka.example.com:9092
      - ORDERER_GENERAL_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_GENERAL_CHANNELPARTICIPATION_PLUGIN= "OR('OrdererMSP.member')"
    volumes:
      - ./crypto-config/ordererOrganizations/example.com/orderers/healthcare_orderer.example.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/example.com/orderers/healthcare_orderer.example.com/orderer.genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    ports:
      - 17052:17050

  patient.example.com:
    container_name: patient.example.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ADDRESS=patient.example.com:17053
      - CORE_PEER_LOCALMSPID=PatientMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=patient.example.com:17053
      - CORE_PEER_POLICY_CHECKER_PLUGIN= "OR('PatientMSP.member')"
    volumes:
      - ./crypto-config/peerOrganizations/example.com/peers/patient.example.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 17053:17053

  hospital.example.com:
    container_name: hospital.example.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ADDRESS=hospital.example.com:17053
      - CORE_PEER_LOCALMSPID=HospitalMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=hospital.example.com:17053
      - CORE_PEER_POLICY_CHECKER_PLUGIN= "OR('HospitalMSP.member')"
    volumes:
      - ./crypto-config/peerOrganizations/example.com/peers/hospital.example.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 18053:17053

  laboratory.example.com:
    container_name: laboratory.example.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ADDRESS=laboratory.example.com:17053
      - CORE_PEER_LOCALMSPID=LaboratoryMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=laboratory.example.com:17053
      - CORE_PEER_POLICY_CHECKER_PLUGIN= "OR('LaboratoryMSP.member')"
    volumes:
      - ./crypto-config/peerOrganizations/example.com/peers/laboratory.example.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 19053:17053

  pharmacy.example.com:
    container_name: pharmacy.example.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ADDRESS=pharmacy.example.com:17053
      - CORE_PEER_LOCALMSPID=PharmacyMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=pharmacy.example.com:17053
      - CORE_PEER_POLICY_CHECKER_PLUGIN= "OR('PharmacyMSP.member')"
    volumes:
      - ./crypto-config/peerOrganizations/example.com/peers/pharmacy.example.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 10053:17053

  insurance.example.com:
    container_name: insurance.example.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ADDRESS=insurance.example.com:17053
      - CORE_PEER_LOCALMSPID=InsuranceMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=insurance.example.com:17053
      - CORE_PEER_POLICY_CHECKER_PLUGIN= "OR('InsuranceMSP.member')"
    volumes:
      - ./crypto-config/peerOrganizations/example.com/peers/insurance.example.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 11053:17053

